TypeError: only length-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/arthur/Library/Mobile Documents/com~apple~CloudDocs/Cours/ECN6338/Devoir à rendre/projet Avec critique/train.py", line 357, in <module>
    master_val, follower_val, iteration, start_time = solve(u_vals, t_vals, B_val, cfg)
                                                      ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arthur/Library/Mobile Documents/com~apple~CloudDocs/Cours/ECN6338/Devoir à rendre/projet Avec critique/train.py", line 85, in solve
    u = np.array(data["u"], dtype=np.float32)
  File "/Users/arthur/miniconda3/envs/GFlowNet-Knapsack-Actor-Critic/lib/python3.13/site-packages/pandas/core/series.py", line 1031, in __array__
    arr = np.asarray(values, dtype=dtype)
ValueError: setting an array element with a sequence.
